
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author chari
 */
public class MCustomerOrderViwe extends javax.swing.JFrame {

    private int userId;
    private JTable ordersTable;
    private JButton editButton, deleteButton;
    private DefaultTableModel tableModel;

    /**
     * Creates new form MCustomerOrderViwe
     */
    public MCustomerOrderViwe(int userId) throws ClassNotFoundException {

        this.userId = userId;
        initComponents();
        setTitle("Customer Orders");
        setSize(800, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
        initializeUI();
    }

    private MCustomerOrderViwe() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        ChangeButton = new javax.swing.JButton();

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        ChangeButton.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        ManagerDashboard managerDashboard = new ManagerDashboard(userId);
        managerDashboard.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MCustomerOrderViwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MCustomerOrderViwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MCustomerOrderViwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MCustomerOrderViwe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MCustomerOrderViwe().setVisible(true);
            }
        });
    }

    private void initializeUI() throws ClassNotFoundException {
        tableModel = new DefaultTableModel(new String[]{"Order ID", "Item Name", "Category", "Quantity", "Special Note", "Total", "Status"}, 0);
        ordersTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(ordersTable);
        add(scrollPane, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel();
        BackButton = new JButton("Back");
        ChangeButton = new JButton("Change Status");

        BackButton.addActionListener(e -> {
            ManagerDashboard managerDashboard = new ManagerDashboard(userId);
            managerDashboard.setVisible(true);
            this.setVisible(false);
        });

        ChangeButton.addActionListener(e -> {
            try {
                ChangeStatus();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CustomerOrderViewForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        buttonPanel.add(BackButton);
        buttonPanel.add(ChangeButton);
        add(buttonPanel, BorderLayout.SOUTH);
        loadOrders();
    }

    private void loadOrders() throws ClassNotFoundException {
        String query = "SELECT order_id, item_name, item_category, item_quantity, special_note, total_price,status FROM customerorders";
        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement pstmt = conn.prepareStatement(query)) {
//            pstmt.setInt(1, userId);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                tableModel.addRow(new Object[]{rs.getInt("order_id"), rs.getString("item_name"), rs.getString("item_category"), rs.getInt("item_quantity"), rs.getString("special_note"), rs.getInt("total_price"), rs.getString("status")});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading orders: " + ex.getMessage());
        }
    }

    private void ChangeStatus() throws ClassNotFoundException {
        int selectedRow = ordersTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an order to change.");
            return;
        }
        // Assuming the first column is the order ID
        int orderId = (Integer) ordersTable.getValueAt(selectedRow, 0);
        // Proceed to fetch the order details and show in an editable form
        editOrderDetails(orderId);
    }

    private void editOrderDetails(int orderId) throws ClassNotFoundException {
        // Placeholder for opening an editing dialog
        StatusEditDialog editDialog = new StatusEditDialog(this, true, orderId);
        editDialog.setVisible(true);
        if (editDialog.isSaved()) {
            loadOrders();  // Reload orders if changes were saved

            ManagerDashboard managerDashboard = new ManagerDashboard(userId);
            managerDashboard.setVisible(true);
            this.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ChangeButton;
    // End of variables declaration//GEN-END:variables
}
